"""add social feed, groups, cart, collection

Revision ID: f407fe8b8649
Revises: f9fc4cc130a2
Create Date: 2026-07-22 14:55:48.183680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f407fe8b8649'
down_revision: Union[str, Sequence[str], None] = 'f9fc4cc130a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communitygroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communitygroup_created_at'), 'communitygroup', ['created_at'], unique=False)
    op.create_index(op.f('ix_communitygroup_kind'), 'communitygroup', ['kind'], unique=False)
    op.create_index(op.f('ix_communitygroup_slug'), 'communitygroup', ['slug'], unique=True)
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_listing_id'), 'cartitem', ['listing_id'], unique=False)
    op.create_index(op.f('ix_cartitem_user_id'), 'cartitem', ['user_id'], unique=False)
    op.create_table('collectionitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collectionitem_created_at'), 'collectionitem', ['created_at'], unique=False)
    op.create_index(op.f('ix_collectionitem_user_id'), 'collectionitem', ['user_id'], unique=False)
    op.create_table('feedpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('market_value_cents', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_story', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedpost_created_at'), 'feedpost', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedpost_is_story'), 'feedpost', ['is_story'], unique=False)
    op.create_index(op.f('ix_feedpost_kind'), 'feedpost', ['kind'], unique=False)
    op.create_index(op.f('ix_feedpost_seller_id'), 'feedpost', ['seller_id'], unique=False)
    op.create_table('groupmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['communitygroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupmember_group_id'), 'groupmember', ['group_id'], unique=False)
    op.create_index(op.f('ix_groupmember_user_id'), 'groupmember', ['user_id'], unique=False)
    op.create_table('groupthread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('is_poll', sa.Boolean(), nullable=False),
    sa.Column('poll_options', sa.JSON(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['communitygroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupthread_created_at'), 'groupthread', ['created_at'], unique=False)
    op.create_index(op.f('ix_groupthread_group_id'), 'groupthread', ['group_id'], unique=False)
    op.create_table('groupcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['groupthread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupcomment_created_at'), 'groupcomment', ['created_at'], unique=False)
    op.create_index(op.f('ix_groupcomment_thread_id'), 'groupcomment', ['thread_id'], unique=False)
    op.add_column('user', sa.Column('supabase_sub', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.create_index(op.f('ix_user_supabase_sub'), 'user', ['supabase_sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_sub'), table_name='user')
    op.drop_column('user', 'supabase_sub')
    op.drop_index(op.f('ix_groupcomment_thread_id'), table_name='groupcomment')
    op.drop_index(op.f('ix_groupcomment_created_at'), table_name='groupcomment')
    op.drop_table('groupcomment')
    op.drop_index(op.f('ix_groupthread_group_id'), table_name='groupthread')
    op.drop_index(op.f('ix_groupthread_created_at'), table_name='groupthread')
    op.drop_table('groupthread')
    op.drop_index(op.f('ix_groupmember_user_id'), table_name='groupmember')
    op.drop_index(op.f('ix_groupmember_group_id'), table_name='groupmember')
    op.drop_table('groupmember')
    op.drop_index(op.f('ix_feedpost_seller_id'), table_name='feedpost')
    op.drop_index(op.f('ix_feedpost_kind'), table_name='feedpost')
    op.drop_index(op.f('ix_feedpost_is_story'), table_name='feedpost')
    op.drop_index(op.f('ix_feedpost_created_at'), table_name='feedpost')
    op.drop_table('feedpost')
    op.drop_index(op.f('ix_collectionitem_user_id'), table_name='collectionitem')
    op.drop_index(op.f('ix_collectionitem_created_at'), table_name='collectionitem')
    op.drop_table('collectionitem')
    op.drop_index(op.f('ix_cartitem_user_id'), table_name='cartitem')
    op.drop_index(op.f('ix_cartitem_listing_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_index(op.f('ix_communitygroup_slug'), table_name='communitygroup')
    op.drop_index(op.f('ix_communitygroup_kind'), table_name='communitygroup')
    op.drop_index(op.f('ix_communitygroup_created_at'), table_name='communitygroup')
    op.drop_table('communitygroup')
    # ### end Alembic commands ###
