"""initial_schema

Revision ID: f9fc4cc130a2
Revises: 
Create Date: 2026-07-20 10:47:41.397331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9fc4cc130a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foundingapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('handle_wanted', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('categories', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('current_platforms', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('monthly_volume', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundingapplication_created_at'), 'foundingapplication', ['created_at'], unique=False)
    op.create_index(op.f('ix_foundingapplication_email'), 'foundingapplication', ['email'], unique=False)
    op.create_index(op.f('ix_foundingapplication_status'), 'foundingapplication', ['status'], unique=False)
    op.create_table('knowledgearticle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgearticle_active'), 'knowledgearticle', ['active'], unique=False)
    op.create_index(op.f('ix_knowledgearticle_category'), 'knowledgearticle', ['category'], unique=False)
    op.create_index(op.f('ix_knowledgearticle_slug'), 'knowledgearticle', ['slug'], unique=True)
    op.create_table('processedstripeevent',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processedstripeevent_processed_at'), 'processedstripeevent', ['processed_at'], unique=False)
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('is_founding', sa.Boolean(), nullable=False),
    sa.Column('founding_number', sa.Integer(), nullable=True),
    sa.Column('founding_activated_at', sa.DateTime(), nullable=True),
    sa.Column('founding_intro_ends_at', sa.DateTime(), nullable=True),
    sa.Column('founding_intro_sales_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('store_public', sa.Boolean(), nullable=False),
    sa.Column('store_edit_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_created_at'), 'seller', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_founding_number'), 'seller', ['founding_number'], unique=False)
    op.create_index(op.f('ix_seller_handle'), 'seller', ['handle'], unique=True)
    op.create_index(op.f('ix_seller_is_founding'), 'seller', ['is_founding'], unique=False)
    op.create_index(op.f('ix_seller_store_edit_token'), 'seller', ['store_edit_token'], unique=False)
    op.create_index(op.f('ix_seller_store_public'), 'seller', ['store_public'], unique=False)
    op.create_index(op.f('ix_seller_stripe_account_id'), 'seller', ['stripe_account_id'], unique=False)
    op.create_table('sitecollaborator',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_sitecollaborator_role'), 'sitecollaborator', ['role'], unique=False)
    op.create_table('sitesetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verify_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('verify_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('reset_sent_at', sa.DateTime(), nullable=True),
    sa.Column('pending_email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller_handle', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_google_sub'), 'user', ['google_sub'], unique=False)
    op.create_index(op.f('ix_user_reset_token'), 'user', ['reset_token'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_seller_handle'), 'user', ['seller_handle'], unique=False)
    op.create_index(op.f('ix_user_verify_token'), 'user', ['verify_token'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_seller_id'), 'follow', ['seller_id'], unique=False)
    op.create_index(op.f('ix_follow_user_id'), 'follow', ['user_id'], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('player_or_character', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grading_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_cents', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image_public_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('image_enhanced', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('seller_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('is_founding_seller', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_category'), 'listing', ['category'], unique=False)
    op.create_index(op.f('ix_listing_condition'), 'listing', ['condition'], unique=False)
    op.create_index(op.f('ix_listing_created_at'), 'listing', ['created_at'], unique=False)
    op.create_index(op.f('ix_listing_grade'), 'listing', ['grade'], unique=False)
    op.create_index(op.f('ix_listing_grading_company'), 'listing', ['grading_company'], unique=False)
    op.create_index(op.f('ix_listing_is_featured'), 'listing', ['is_featured'], unique=False)
    op.create_index(op.f('ix_listing_is_founding_seller'), 'listing', ['is_founding_seller'], unique=False)
    op.create_index(op.f('ix_listing_is_graded'), 'listing', ['is_graded'], unique=False)
    op.create_index(op.f('ix_listing_player_or_character'), 'listing', ['player_or_character'], unique=False)
    op.create_index(op.f('ix_listing_price_cents'), 'listing', ['price_cents'], unique=False)
    op.create_index(op.f('ix_listing_seller_id'), 'listing', ['seller_id'], unique=False)
    op.create_index(op.f('ix_listing_seller_name'), 'listing', ['seller_name'], unique=False)
    op.create_index(op.f('ix_listing_set_name'), 'listing', ['set_name'], unique=False)
    op.create_index(op.f('ix_listing_status'), 'listing', ['status'], unique=False)
    op.create_index(op.f('ix_listing_title'), 'listing', ['title'], unique=False)
    op.create_table('livestream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embed_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestream_created_at'), 'livestream', ['created_at'], unique=False)
    op.create_index(op.f('ix_livestream_seller_id'), 'livestream', ['seller_id'], unique=False)
    op.create_index(op.f('ix_livestream_status'), 'livestream', ['status'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_read'), 'notification', ['read'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('savedsearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savedsearch_user_id'), 'savedsearch', ['user_id'], unique=False)
    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_expires_at'), 'usersession', ['expires_at'], unique=False)
    op.create_index(op.f('ix_usersession_token'), 'usersession', ['token'], unique=True)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.create_table('wantitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wantitem_category'), 'wantitem', ['category'], unique=False)
    op.create_index(op.f('ix_wantitem_created_at'), 'wantitem', ['created_at'], unique=False)
    op.create_index(op.f('ix_wantitem_status'), 'wantitem', ['status'], unique=False)
    op.create_index(op.f('ix_wantitem_user_id'), 'wantitem', ['user_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_seller_id'), 'conversation', ['seller_id'], unique=False)
    op.create_index(op.f('ix_conversation_updated_at'), 'conversation', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_table('inventoryhold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('stripe_session_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryhold_buyer_user_id'), 'inventoryhold', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_inventoryhold_converted'), 'inventoryhold', ['converted'], unique=False)
    op.create_index(op.f('ix_inventoryhold_expires_at'), 'inventoryhold', ['expires_at'], unique=False)
    op.create_index(op.f('ix_inventoryhold_listing_id'), 'inventoryhold', ['listing_id'], unique=False)
    op.create_index(op.f('ix_inventoryhold_released'), 'inventoryhold', ['released'], unique=False)
    op.create_index(op.f('ix_inventoryhold_stripe_session_id'), 'inventoryhold', ['stripe_session_id'], unique=True)
    op.create_table('livestreamreminder',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['livestream.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stream_id')
    )
    op.create_index(op.f('ix_livestreamreminder_created_at'), 'livestreamreminder', ['created_at'], unique=False)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('counter_amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_buyer_user_id'), 'offer', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_offer_created_at'), 'offer', ['created_at'], unique=False)
    op.create_index(op.f('ix_offer_listing_id'), 'offer', ['listing_id'], unique=False)
    op.create_index(op.f('ix_offer_seller_id'), 'offer', ['seller_id'], unique=False)
    op.create_index(op.f('ix_offer_status'), 'offer', ['status'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('buyer_email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('stripe_session_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('stripe_refund_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('refunded_cents', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_buyer_user_id'), 'order', ['buyer_user_id'], unique=False)
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_listing_id'), 'order', ['listing_id'], unique=False)
    op.create_index(op.f('ix_order_seller_id'), 'order', ['seller_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_stripe_refund_id'), 'order', ['stripe_refund_id'], unique=False)
    op.create_index(op.f('ix_order_stripe_session_id'), 'order', ['stripe_session_id'], unique=False)
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=True),
    sa.Column('apis', sa.JSON(), nullable=True),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phase_started_at', sa.DateTime(), nullable=True),
    sa.Column('phase_ends_at', sa.DateTime(), nullable=True),
    sa.Column('starting_bid_cents', sa.Integer(), nullable=False),
    sa.Column('reserve_cents', sa.Integer(), nullable=False),
    sa.Column('current_bid_cents', sa.Integer(), nullable=False),
    sa.Column('current_bidder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_price_cents', sa.Integer(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_created_at'), 'ride', ['created_at'], unique=False)
    op.create_index(op.f('ix_ride_seller_id'), 'ride', ['seller_id'], unique=False)
    op.create_index(op.f('ix_ride_status'), 'ride', ['status'], unique=False)
    op.create_index(op.f('ix_ride_type'), 'ride', ['type'], unique=False)
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('player_or_character', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('grading_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sold_price_cents', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_card_number'), 'sale', ['card_number'], unique=False)
    op.create_index(op.f('ix_sale_category'), 'sale', ['category'], unique=False)
    op.create_index(op.f('ix_sale_grade'), 'sale', ['grade'], unique=False)
    op.create_index(op.f('ix_sale_grading_company'), 'sale', ['grading_company'], unique=False)
    op.create_index(op.f('ix_sale_is_graded'), 'sale', ['is_graded'], unique=False)
    op.create_index(op.f('ix_sale_listing_id'), 'sale', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sale_player_or_character'), 'sale', ['player_or_character'], unique=False)
    op.create_index(op.f('ix_sale_set_name'), 'sale', ['set_name'], unique=False)
    op.create_index(op.f('ix_sale_sold_at'), 'sale', ['sold_at'], unique=False)
    op.create_index(op.f('ix_sale_sold_price_cents'), 'sale', ['sold_price_cents'], unique=False)
    op.create_index(op.f('ix_sale_source'), 'sale', ['source'], unique=False)
    op.create_table('watchitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchitem_listing_id'), 'watchitem', ['listing_id'], unique=False)
    op.create_index(op.f('ix_watchitem_user_id'), 'watchitem', ['user_id'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('bidder', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('bidder_user_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_amount_cents'), 'bid', ['amount_cents'], unique=False)
    op.create_index(op.f('ix_bid_bidder_user_id'), 'bid', ['bidder_user_id'], unique=False)
    op.create_index(op.f('ix_bid_created_at'), 'bid', ['created_at'], unique=False)
    op.create_index(op.f('ix_bid_ride_id'), 'bid', ['ride_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_conversation_id'), 'chatmessage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_created_at'), 'chatmessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatmessage_read'), 'chatmessage', ['read'], unique=False)
    op.create_table('dispute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_created_at'), 'dispute', ['created_at'], unique=False)
    op.create_index(op.f('ix_dispute_order_id'), 'dispute', ['order_id'], unique=False)
    op.create_index(op.f('ix_dispute_status'), 'dispute', ['status'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('rater_user_id', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['rater_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_order_id'), 'feedback', ['order_id'], unique=True)
    op.create_index(op.f('ix_feedback_seller_id'), 'feedback', ['seller_id'], unique=False)
    op.create_table('giveaway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_giveaway_created_at'), 'giveaway', ['created_at'], unique=False)
    op.create_index(op.f('ix_giveaway_ride_id'), 'giveaway', ['ride_id'], unique=False)
    op.create_index(op.f('ix_giveaway_status'), 'giveaway', ['status'], unique=False)
    op.create_table('rideevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rideevent_created_at'), 'rideevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_rideevent_ride_id'), 'rideevent', ['ride_id'], unique=False)
    op.create_index(op.f('ix_rideevent_type'), 'rideevent', ['type'], unique=False)
    op.create_table('supportconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('queue', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('workflow', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('workflow_step', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportconversation_channel'), 'supportconversation', ['channel'], unique=False)
    op.create_index(op.f('ix_supportconversation_created_at'), 'supportconversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportconversation_intent'), 'supportconversation', ['intent'], unique=False)
    op.create_index(op.f('ix_supportconversation_order_id'), 'supportconversation', ['order_id'], unique=False)
    op.create_index(op.f('ix_supportconversation_public_id'), 'supportconversation', ['public_id'], unique=True)
    op.create_index(op.f('ix_supportconversation_queue'), 'supportconversation', ['queue'], unique=False)
    op.create_index(op.f('ix_supportconversation_status'), 'supportconversation', ['status'], unique=False)
    op.create_index(op.f('ix_supportconversation_updated_at'), 'supportconversation', ['updated_at'], unique=False)
    op.create_index(op.f('ix_supportconversation_user_id'), 'supportconversation', ['user_id'], unique=False)
    op.create_table('giveawayentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaway.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_giveawayentry_giveaway_id'), 'giveawayentry', ['giveaway_id'], unique=False)
    op.create_table('supportauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('policy_refs', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['supportconversation.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportauditlog_conversation_id'), 'supportauditlog', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_supportauditlog_created_at'), 'supportauditlog', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportauditlog_order_id'), 'supportauditlog', ['order_id'], unique=False)
    op.create_index(op.f('ix_supportauditlog_user_id'), 'supportauditlog', ['user_id'], unique=False)
    op.create_table('supportmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['supportconversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportmessage_conversation_id'), 'supportmessage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_supportmessage_created_at'), 'supportmessage', ['created_at'], unique=False)
    op.create_table('supportrefund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('stripe_refund_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('issued_by', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['supportconversation.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportrefund_conversation_id'), 'supportrefund', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_supportrefund_created_at'), 'supportrefund', ['created_at'], unique=False)
    op.create_index(op.f('ix_supportrefund_order_id'), 'supportrefund', ['order_id'], unique=False)
    op.create_index(op.f('ix_supportrefund_status'), 'supportrefund', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supportrefund_status'), table_name='supportrefund')
    op.drop_index(op.f('ix_supportrefund_order_id'), table_name='supportrefund')
    op.drop_index(op.f('ix_supportrefund_created_at'), table_name='supportrefund')
    op.drop_index(op.f('ix_supportrefund_conversation_id'), table_name='supportrefund')
    op.drop_table('supportrefund')
    op.drop_index(op.f('ix_supportmessage_created_at'), table_name='supportmessage')
    op.drop_index(op.f('ix_supportmessage_conversation_id'), table_name='supportmessage')
    op.drop_table('supportmessage')
    op.drop_index(op.f('ix_supportauditlog_user_id'), table_name='supportauditlog')
    op.drop_index(op.f('ix_supportauditlog_order_id'), table_name='supportauditlog')
    op.drop_index(op.f('ix_supportauditlog_created_at'), table_name='supportauditlog')
    op.drop_index(op.f('ix_supportauditlog_conversation_id'), table_name='supportauditlog')
    op.drop_table('supportauditlog')
    op.drop_index(op.f('ix_giveawayentry_giveaway_id'), table_name='giveawayentry')
    op.drop_table('giveawayentry')
    op.drop_index(op.f('ix_supportconversation_user_id'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_updated_at'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_status'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_queue'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_public_id'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_order_id'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_intent'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_created_at'), table_name='supportconversation')
    op.drop_index(op.f('ix_supportconversation_channel'), table_name='supportconversation')
    op.drop_table('supportconversation')
    op.drop_index(op.f('ix_rideevent_type'), table_name='rideevent')
    op.drop_index(op.f('ix_rideevent_ride_id'), table_name='rideevent')
    op.drop_index(op.f('ix_rideevent_created_at'), table_name='rideevent')
    op.drop_table('rideevent')
    op.drop_index(op.f('ix_giveaway_status'), table_name='giveaway')
    op.drop_index(op.f('ix_giveaway_ride_id'), table_name='giveaway')
    op.drop_index(op.f('ix_giveaway_created_at'), table_name='giveaway')
    op.drop_table('giveaway')
    op.drop_index(op.f('ix_feedback_seller_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_order_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_dispute_status'), table_name='dispute')
    op.drop_index(op.f('ix_dispute_order_id'), table_name='dispute')
    op.drop_index(op.f('ix_dispute_created_at'), table_name='dispute')
    op.drop_table('dispute')
    op.drop_index(op.f('ix_chatmessage_read'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_created_at'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_conversation_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_bid_ride_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_created_at'), table_name='bid')
    op.drop_index(op.f('ix_bid_bidder_user_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_amount_cents'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_watchitem_user_id'), table_name='watchitem')
    op.drop_index(op.f('ix_watchitem_listing_id'), table_name='watchitem')
    op.drop_table('watchitem')
    op.drop_index(op.f('ix_sale_source'), table_name='sale')
    op.drop_index(op.f('ix_sale_sold_price_cents'), table_name='sale')
    op.drop_index(op.f('ix_sale_sold_at'), table_name='sale')
    op.drop_index(op.f('ix_sale_set_name'), table_name='sale')
    op.drop_index(op.f('ix_sale_player_or_character'), table_name='sale')
    op.drop_index(op.f('ix_sale_listing_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_is_graded'), table_name='sale')
    op.drop_index(op.f('ix_sale_grading_company'), table_name='sale')
    op.drop_index(op.f('ix_sale_grade'), table_name='sale')
    op.drop_index(op.f('ix_sale_category'), table_name='sale')
    op.drop_index(op.f('ix_sale_card_number'), table_name='sale')
    op.drop_table('sale')
    op.drop_index(op.f('ix_ride_type'), table_name='ride')
    op.drop_index(op.f('ix_ride_status'), table_name='ride')
    op.drop_index(op.f('ix_ride_seller_id'), table_name='ride')
    op.drop_index(op.f('ix_ride_created_at'), table_name='ride')
    op.drop_table('ride')
    op.drop_index(op.f('ix_order_stripe_session_id'), table_name='order')
    op.drop_index(op.f('ix_order_stripe_refund_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_seller_id'), table_name='order')
    op.drop_index(op.f('ix_order_listing_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_user_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_offer_status'), table_name='offer')
    op.drop_index(op.f('ix_offer_seller_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_listing_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_created_at'), table_name='offer')
    op.drop_index(op.f('ix_offer_buyer_user_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_livestreamreminder_created_at'), table_name='livestreamreminder')
    op.drop_table('livestreamreminder')
    op.drop_index(op.f('ix_inventoryhold_stripe_session_id'), table_name='inventoryhold')
    op.drop_index(op.f('ix_inventoryhold_released'), table_name='inventoryhold')
    op.drop_index(op.f('ix_inventoryhold_listing_id'), table_name='inventoryhold')
    op.drop_index(op.f('ix_inventoryhold_expires_at'), table_name='inventoryhold')
    op.drop_index(op.f('ix_inventoryhold_converted'), table_name='inventoryhold')
    op.drop_index(op.f('ix_inventoryhold_buyer_user_id'), table_name='inventoryhold')
    op.drop_table('inventoryhold')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_updated_at'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_seller_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_wantitem_user_id'), table_name='wantitem')
    op.drop_index(op.f('ix_wantitem_status'), table_name='wantitem')
    op.drop_index(op.f('ix_wantitem_created_at'), table_name='wantitem')
    op.drop_index(op.f('ix_wantitem_category'), table_name='wantitem')
    op.drop_table('wantitem')
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_token'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_expires_at'), table_name='usersession')
    op.drop_table('usersession')
    op.drop_index(op.f('ix_savedsearch_user_id'), table_name='savedsearch')
    op.drop_table('savedsearch')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_livestream_status'), table_name='livestream')
    op.drop_index(op.f('ix_livestream_seller_id'), table_name='livestream')
    op.drop_index(op.f('ix_livestream_created_at'), table_name='livestream')
    op.drop_table('livestream')
    op.drop_index(op.f('ix_listing_title'), table_name='listing')
    op.drop_index(op.f('ix_listing_status'), table_name='listing')
    op.drop_index(op.f('ix_listing_set_name'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_name'), table_name='listing')
    op.drop_index(op.f('ix_listing_seller_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_price_cents'), table_name='listing')
    op.drop_index(op.f('ix_listing_player_or_character'), table_name='listing')
    op.drop_index(op.f('ix_listing_is_graded'), table_name='listing')
    op.drop_index(op.f('ix_listing_is_founding_seller'), table_name='listing')
    op.drop_index(op.f('ix_listing_is_featured'), table_name='listing')
    op.drop_index(op.f('ix_listing_grading_company'), table_name='listing')
    op.drop_index(op.f('ix_listing_grade'), table_name='listing')
    op.drop_index(op.f('ix_listing_created_at'), table_name='listing')
    op.drop_index(op.f('ix_listing_condition'), table_name='listing')
    op.drop_index(op.f('ix_listing_category'), table_name='listing')
    op.drop_table('listing')
    op.drop_index(op.f('ix_follow_user_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_seller_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index(op.f('ix_user_verify_token'), table_name='user')
    op.drop_index(op.f('ix_user_seller_handle'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_google_sub'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_table('sitesetting')
    op.drop_index(op.f('ix_sitecollaborator_role'), table_name='sitecollaborator')
    op.drop_table('sitecollaborator')
    op.drop_index(op.f('ix_seller_stripe_account_id'), table_name='seller')
    op.drop_index(op.f('ix_seller_store_public'), table_name='seller')
    op.drop_index(op.f('ix_seller_store_edit_token'), table_name='seller')
    op.drop_index(op.f('ix_seller_is_founding'), table_name='seller')
    op.drop_index(op.f('ix_seller_handle'), table_name='seller')
    op.drop_index(op.f('ix_seller_founding_number'), table_name='seller')
    op.drop_index(op.f('ix_seller_created_at'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_processedstripeevent_processed_at'), table_name='processedstripeevent')
    op.drop_table('processedstripeevent')
    op.drop_index(op.f('ix_knowledgearticle_slug'), table_name='knowledgearticle')
    op.drop_index(op.f('ix_knowledgearticle_category'), table_name='knowledgearticle')
    op.drop_index(op.f('ix_knowledgearticle_active'), table_name='knowledgearticle')
    op.drop_table('knowledgearticle')
    op.drop_index(op.f('ix_foundingapplication_status'), table_name='foundingapplication')
    op.drop_index(op.f('ix_foundingapplication_email'), table_name='foundingapplication')
    op.drop_index(op.f('ix_foundingapplication_created_at'), table_name='foundingapplication')
    op.drop_table('foundingapplication')
    # ### end Alembic commands ###
